---
galaxy_info:
  author: TannerFilip
  role_name: malbox_document_analysis
  description: Install Didier Stevens document analysis tools (pdfid, pdf-parser, oledump).
  license: MIT
  min_ansible_version: "2.14"
  platforms:
    - name: Ubuntu
      versions: all
    - name: Debian
      versions: all
dependencies: []
