---
__malbox_base_packages:
  - curl
  - wget
  - git
  - vim
  - nano
  - tmux
  - ripgrep
  - bat
  - jq
  - libxml2-utils
  - xxd
  - file
  - unzip
  - p7zip-full
  - cabextract
  - unrar-free
  - build-essential
  - ca-certificates
  - gnupg
