---
galaxy_info:
  role_name: malbox_network
  description: Install network analysis tools for a malware analysis workstation.
  license: MIT
  min_ansible_version: "2.14"
  platforms:
    - name: Ubuntu
      versions: all
    - name: Debian
      versions: all
dependencies: []
