---
- name: malbox_node_tools | Install Node.js via geerlingguy.nodejs
  ansible.builtin.include_role:
    name: geerlingguy.nodejs
  vars:
    nodejs_version: "{{ malbox_node_tools_node_version }}"
    nodejs_npm_global_packages: "{{ __malbox_node_tools_npm_packages }}"
  tags: malbox_node_tools
