---
- name: malbox_node_tools | Install nvm and Node.js via ansible-role-nvm
  ansible.builtin.include_role:
    name: morgangraphics.ansible_role_nvm
  vars:
    nvm_version: "{{ malbox_node_tools_nvm_version }}"
    nodejs_version: "{{ malbox_node_tools_node_version }}"
    nvm_install: curl
  become_user: "{{ malbox_node_tools_user }}"
  tags: malbox_node_tools

- name: malbox_node_tools | Install JavaScript analysis tools
  ansible.builtin.shell:
    cmd: source $HOME/.nvm/nvm.sh && npm install -g {{ item }}
    executable: /bin/bash
  become_user: "{{ malbox_node_tools_user }}"
  loop: "{{ __malbox_node_tools_npm_packages }}"
  tags: malbox_node_tools
