---
galaxy_info:
  author: TannerFilip
  role_name: malbox_yara
  description: Download and install YARA Forge community rulesets.
  license: MIT
  min_ansible_version: "2.14"
  platforms:
    - name: Ubuntu
      versions: all
    - name: Debian
      versions: all
dependencies: []
